CREATE TABLE Sales
(
ES_id CHAR(5),
PS_id CHAR(5),
S_number INT NOT NULL,
PRIMARY KEY(ES_id, PS_id),
FOREIGN KEY(ES_id)REFERENCES Employee(Em_id)
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY(PS_id)REFERENCES Product(P_id)
)