CREATE TABLE Order_details
(
OC_id CHAR(5),
OP_id CHAR(5),
Number INT NOT NULL,
PRIMARY KEY(OC_id, OP_id),
FOREIGN KEY(OC_id)REFERENCES Client(C_id)
ON UPDATE CASCADE
ON DELETE CASCADE,
FOREIGN KEY(OP_id)REFERENCES Product2(P2_id)
)